import re

palavras_positivas = [
    re.compile(r"\bbom\b", re.IGNORECASE),
    re.compile(r"\bmuito bom\b", re.IGNORECASE),
    re.compile(r"\blegal\w*\b", re.IGNORECASE),
    re.compile(r"\bótimo\b", re.IGNORECASE),
    re.compile(r"\bexcelente\b", re.IGNORECASE),
    re.compile(r"\binteressante\b", re.IGNORECASE),
    re.compile(r"\bdivertid\w+\b", re.IGNORECASE),
    re.compile(r"\bemocionante\b", re.IGNORECASE),
    re.compile(r"\btocante\b", re.IGNORECASE),
    re.compile(r"\bemociona\b", re.IGNORECASE),
    re.compile(r"\bemocional\b", re.IGNORECASE),
    re.compile(r"\bam\w+\b", re.IGNORECASE),
    re.compile(r"\bgost\w+\b", re.IGNORECASE),
    re.compile(r"\bador\w+\b", re.IGNORECASE),
    re.compile(r"\bincrível\b", re.IGNORECASE),
    re.compile(r"\bimpressionante\b", re.IGNORECASE),
    re.compile(r"\brecomendo\b", re.IGNORECASE),
    re.compile(r"\bobra-prima\b", re.IGNORECASE),
    re.compile(r"\bsensacional\b", re.IGNORECASE),
    re.compile(r"\bespetacular\b", re.IGNORECASE),
    re.compile(r"\bfantástico\b", re.IGNORECASE),
    re.compile(r"\bmaravilhoso\b", re.IGNORECASE),
    re.compile(r"\bperfeito\b", re.IGNORECASE),
    re.compile(r"\bfenomenal\b", re.IGNORECASE),
    re.compile(r"\bdeslumbrante\b", re.IGNORECASE),
    re.compile(r"\bsurpreendente\b", re.IGNORECASE),
    re.compile(r"\bimpecável\b", re.IGNORECASE),
    re.compile(r"\bcativante\b", re.IGNORECASE),
    re.compile(r"\benvolvente\b", re.IGNORECASE),
    re.compile(r"\bmagnífico\b", re.IGNORECASE),
    re.compile(r"\bextraordinário\b", re.IGNORECASE),
    re.compile(r"\bapaixonante\b", re.IGNORECASE),
    re.compile(r"\bcomovente\b", re.IGNORECASE),
    re.compile(r"\binspirador\b", re.IGNORECASE),
    re.compile(r"\bmemorável\b", re.IGNORECASE),
    re.compile(r"\binesquecível\b", re.IGNORECASE),
    re.compile(r"\búnico\b", re.IGNORECASE),
    re.compile(r"\bgenial\b", re.IGNORECASE),
    re.compile(r"\bbrilhante\b", re.IGNORECASE),
    re.compile(r"\bexcepcional\b", re.IGNORECASE),
    re.compile(r"\badorável\b", re.IGNORECASE),
    re.compile(r"\bapaixonante\b", re.IGNORECASE),
    re.compile(r"\bentusiasmante\b", re.IGNORECASE),
    re.compile(r"\balegre\b", re.IGNORECASE),
    re.compile(r"\bempolgante\b", re.IGNORECASE),
    re.compile(r"\bpositivo\b", re.IGNORECASE),
    re.compile(r"\bcarismático\b", re.IGNORECASE),
    re.compile(r"\bcarismática\b", re.IGNORECASE),
    re.compile(r"\bcativou\b", re.IGNORECASE),
    re.compile(r"\benriquece\b", re.IGNORECASE),
    re.compile(r"\belogiável\b", re.IGNORECASE),
    re.compile(r"\bagradável\b", re.IGNORECASE),
    re.compile(r"\bemocionou\b", re.IGNORECASE),
    re.compile(r"\btraz alegria\b", re.IGNORECASE),
    re.compile(r"\bbrilhantemente\b", re.IGNORECASE),
    re.compile(r"\barrebatador\b", re.IGNORECASE),
    re.compile(r"\barrebatadora\b", re.IGNORECASE),
    re.compile(r"\batuações impecáveis\b", re.IGNORECASE),
    re.compile(r"\broteiro afiado\b", re.IGNORECASE),
    re.compile(r"\bfotografia linda\b", re.IGNORECASE),
    re.compile(r"\btrilha sonora perfeita\b", re.IGNORECASE),
    re.compile(r"\bdireção magistral\b", re.IGNORECASE),
    re.compile(r"\bdelicioso\b", re.IGNORECASE),
    re.compile(r"\bmarcante\b", re.IGNORECASE),
    re.compile(r"\bprofundo\b", re.IGNORECASE),
    re.compile(r"\bcom muita qualidade\b", re.IGNORECASE),
    re.compile(r"\bcoroa a carreira\b", re.IGNORECASE),
    re.compile(r"\bobra de arte\b", re.IGNORECASE),
    re.compile(r"\bexuberante\b", re.IGNORECASE),
    re.compile(r"\bcriação incrível\b", re.IGNORECASE),
    re.compile(r"\bfez rir\b", re.IGNORECASE),
    re.compile(r"\bfez chorar\b", re.IGNORECASE),
    re.compile(r"\bentretém do começo ao fim\b", re.IGNORECASE),
    re.compile(r"\bvale a pena\b", re.IGNORECASE),
    re.compile(r"\buma jóia\b", re.IGNORECASE),
    re.compile(r"\bgrande atuação\b", re.IGNORECASE),
    re.compile(r"\binterpretação brilhante\b", re.IGNORECASE),
    re.compile(r"\bencantador\b", re.IGNORECASE),
    re.compile(r"\bencantadora\b", re.IGNORECASE),
    re.compile(r"\bsutilmente poderoso\b", re.IGNORECASE),
    re.compile(r"\bmuito bem feito\b", re.IGNORECASE),
    re.compile(r"\bcom classe\b", re.IGNORECASE),
    re.compile(r"\bcom maestria\b", re.IGNORECASE),
    re.compile(r"\bmuito inteligente\b", re.IGNORECASE),
    re.compile(r"\bdetalhes incríveis\b", re.IGNORECASE),
    re.compile(r"\bsurpreende\b", re.IGNORECASE),
    re.compile(r"\benvolve\b", re.IGNORECASE),
    re.compile(r"\bimpactante\b", re.IGNORECASE),
    re.compile(r"\bcarregado de emoção\b", re.IGNORECASE),
    re.compile(r"\bcom ótimas sacadas\b", re.IGNORECASE),
    re.compile(r"\bfinal brilhante\b", re.IGNORECASE),
    re.compile(r"\bvaloriza a experiência\b", re.IGNORECASE),
    re.compile(r"\bum presente para os fãs\b", re.IGNORECASE),
    re.compile(r"\btrabalho primoroso\b", re.IGNORECASE),
    re.compile(r"\brealização magnífica\b", re.IGNORECASE),
    re.compile(r"\buma grata surpresa\b", re.IGNORECASE),
    re.compile(r"\btransborda talento\b", re.IGNORECASE),
    re.compile(r"\bfilme poderoso\b", re.IGNORECASE),
]

import re

palavras_negativas = [
    re.compile(r"\bruim\b", re.IGNORECASE),
    re.compile(r"\bmuito ruim\b", re.IGNORECASE),
    re.compile(r"\bpéssim\w+\b", re.IGNORECASE),
    re.compile(r"\bchat\w+\b", re.IGNORECASE),
    re.compile(r"\bterrível\b", re.IGNORECASE),
    re.compile(r"\bsem graça\b", re.IGNORECASE),
    re.compile(r"\bfraco\b", re.IGNORECASE),
    re.compile(r"\bsofrível\b", re.IGNORECASE),
    re.compile(r"\bmau\b", re.IGNORECASE),
    re.compile(r"\birritante\b", re.IGNORECASE),
    re.compile(r"\bdá raiva\b", re.IGNORECASE),
    re.compile(r"\bfrustrante\b", re.IGNORECASE),
    re.compile(r"\bdecepcionante\b", re.IGNORECASE),
    re.compile(r"\bmedíocre\b", re.IGNORECASE),
    re.compile(r"\bchato\b", re.IGNORECASE),
    re.compile(r"\barrasante\b", re.IGNORECASE),
    re.compile(r"\bentediant\w+\b", re.IGNORECASE),
    re.compile(r"\bdesapontante\b", re.IGNORECASE),
    re.compile(r"\bdesperdício\b", re.IGNORECASE),
    re.compile(r"\binassistível\b", re.IGNORECASE),
    re.compile(r"\barrastado\b", re.IGNORECASE),
    re.compile(r"\bconfuso\b", re.IGNORECASE),
    re.compile(r"\bmal feito\b", re.IGNORECASE),
    re.compile(r"\bdifícil de assistir\b", re.IGNORECASE),
    re.compile(r"\bincompreensível\b", re.IGNORECASE),
    re.compile(r"\binsuportável\b", re.IGNORECASE),
    re.compile(r"\bdesinteressante\b", re.IGNORECASE),
    re.compile(r"\bincoerente\b", re.IGNORECASE),
    re.compile(r"\bsem conteúdo\b", re.IGNORECASE),
    re.compile(r"\bmá interpretação\b", re.IGNORECASE),
    re.compile(r"\bsem emoção\b", re.IGNORECASE),
    re.compile(r"\bbaixo orçamento\b", re.IGNORECASE),
    re.compile(r"\bprevisível\b", re.IGNORECASE),
    re.compile(r"\bexagerado\b", re.IGNORECASE),
    re.compile(r"\bsem ritmo\b", re.IGNORECASE),
    re.compile(r"\bmonótono\b", re.IGNORECASE),
    re.compile(r"\binsignificante\b", re.IGNORECASE),
    re.compile(r"\bsem profundidade\b", re.IGNORECASE),
    re.compile(r"\bsem sentido\b", re.IGNORECASE),
    re.compile(r"\bsem lógica\b", re.IGNORECASE),
    re.compile(r"\bem cima da hora\b", re.IGNORECASE),
    re.compile(r"\bmal escrito\b", re.IGNORECASE),
    re.compile(r"\bpior que o esperado\b", re.IGNORECASE),
    re.compile(r"\bdesleixado\b", re.IGNORECASE),
    re.compile(r"\bcaótico\b", re.IGNORECASE),
    re.compile(r"\bsem carisma\b", re.IGNORECASE),
    re.compile(r"\bsem autenticidade\b", re.IGNORECASE),
    re.compile(r"\bpéssimo gosto\b", re.IGNORECASE),
    re.compile(r"\bdetalhes falhos\b", re.IGNORECASE),
    re.compile(r"\bsem graça\b", re.IGNORECASE),
    re.compile(r"\bmuito previsível\b", re.IGNORECASE),
    re.compile(r"\bfraco argumento\b", re.IGNORECASE),
    re.compile(r"\bdescompensado\b", re.IGNORECASE),
    re.compile(r"\bsubestimado\b", re.IGNORECASE),
    re.compile(r"\bsem alma\b", re.IGNORECASE),
    re.compile(r"\bsem criatividade\b", re.IGNORECASE),
    re.compile(r"\bsem foco\b", re.IGNORECASE),
    re.compile(r"\bsem personalidade\b", re.IGNORECASE),
    re.compile(r"\bnada a ver\b", re.IGNORECASE),
    re.compile(r"\bemcaminhado\b", re.IGNORECASE),
    re.compile(r"\bsem consistência\b", re.IGNORECASE),
    re.compile(r"\bsem propósito\b", re.IGNORECASE),
    re.compile(r"\bdecepcionou profundamente\b", re.IGNORECASE),
    re.compile(r"\btriste\b", re.IGNORECASE),
    re.compile(r"\bmonótono\b", re.IGNORECASE),
    re.compile(r"\bsem impacto\b", re.IGNORECASE),
    re.compile(r"\btrágico\b", re.IGNORECASE),
    re.compile(r"\bnão vale a pena\b", re.IGNORECASE),
    re.compile(r"\bterrível de se assistir\b", re.IGNORECASE),
    re.compile(r"\bdesinteressado\b", re.IGNORECASE),
    re.compile(r"\bdifícil de gostar\b", re.IGNORECASE),
    re.compile(r"\bsem graça nenhuma\b", re.IGNORECASE),
    re.compile(r"\binacabado\b", re.IGNORECASE),
    re.compile(r"\bnojent\w+\b", re.IGNORECASE),
    re.compile(r"\bdesordenado\b", re.IGNORECASE),
    re.compile(r"\bembaraçoso\b", re.IGNORECASE),
    re.compile(r"\bfrustrante demais\b", re.IGNORECASE),
    re.compile(r"\bsem impacto emocional\b", re.IGNORECASE),
    re.compile(r"\bdecepcionante até o final\b", re.IGNORECASE),
    re.compile(r"\bforçado\b", re.IGNORECASE),
    re.compile(r"\bdesastroso\b", re.IGNORECASE),
    re.compile(r"\bnegativo\b", re.IGNORECASE),
    re.compile(r"\bsem autenticidade\b", re.IGNORECASE),
    re.compile(r"\bterrível direção\b", re.IGNORECASE),
    re.compile(r"\bdireção sem foco\b", re.IGNORECASE),
    re.compile(r"\binválido\b", re.IGNORECASE),
    re.compile(r"\bsem história\b", re.IGNORECASE),
    re.compile(r"\bsem humor\b", re.IGNORECASE),
    re.compile(r"\bsem carisma algum\b", re.IGNORECASE),
    re.compile(r"\bmedíocre direção\b", re.IGNORECASE),
    re.compile(r"\bincompleto\b", re.IGNORECASE),
    re.compile(r"\bdeficiente\b", re.IGNORECASE),
    re.compile(r"\bmá escolha de elenco\b", re.IGNORECASE),
    re.compile(r"\bperda de tempo\b", re.IGNORECASE),
    re.compile(r"\btriste realidade\b", re.IGNORECASE),
    re.compile(r"\bdesgastante\b", re.IGNORECASE),
    re.compile(r"\bdesaproveitado\b", re.IGNORECASE),
    re.compile(r"\bsem nuances\b", re.IGNORECASE),
    re.compile(r"\bdesinteressante\b", re.IGNORECASE),
    re.compile(r"\bsem esforço\b", re.IGNORECASE),
    re.compile(r"\bsem sabor\b", re.IGNORECASE),
    re.compile(r"\bsem propósito claro\b", re.IGNORECASE),
    re.compile(r"\bfragilidade\b", re.IGNORECASE),
    re.compile(r"\bdifícil de engolir\b", re.IGNORECASE),
    re.compile(r"\bnão é bom\b", re.IGNORECASE),
    re.compile(r"\bpéssima\b", re.IGNORECASE),
    re.compile(r"\bdecepcionante\b", re.IGNORECASE),
]